# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZaloraAssignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZaloraAssignment
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SVProgressHUD'
  target 'ZaloraAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
  end

end
